services:
  db:
    image: postgres:17-alpine
    container_name: app-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ucms
    networks:
      - app-network
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public # Mount your public folder to Apache document root
      - ./src:/var/www/html/src # Mount your src folder (accessible within container but not web-accessible)
      - ./vendor:/var/www/html/vendor
      - ./apache/vhost.conf:/etc/apache2/sites-available/000-default.conf # Custom vhost config
      - ./php/conf.d:/usr/local/etc/php/conf.d # Optional: Mount custom PHP configurations
    networks:
      - app-network
    environment:
      # Database connection environment variables for PHP application
      DB_HOST: db # Service name 'db' resolves to the db container's IP within the Docker network
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: ucms
    depends_on:
      - db
    working_dir: /var/www/html/public # Set working directory to public for PHP scripts

volumes:
  db_data:
    # Named volume for PostgreSQL data persistence

networks:
  app-network:
    driver: bridge
